import { MarkerType } from "@xyflow/react";

const zoneStyle = {
  background: "rgba(13, 14, 17, 0.48)",
  border: "1px solid rgba(255,255,255,0.075)",
  borderRadius: 16,
};

export const workflowNodes = [
  {
    id: "story-zone",
    type: "zone",
    position: { x: 40, y: 64 },
    data: { label: "故事理解", tone: "blue" },
    style: { ...zoneStyle, width: 430, height: 560 },
    selectable: false,
    draggable: false,
  },
  {
    id: "visual-zone",
    type: "zone",
    position: { x: 505, y: 64 },
    data: { label: "视觉设定", tone: "violet" },
    style: { ...zoneStyle, width: 470, height: 560 },
    selectable: false,
    draggable: false,
  },
  {
    id: "shot-zone",
    type: "zone",
    position: { x: 1050, y: 64 },
    data: { label: "镜头生成", tone: "cyan" },
    style: { ...zoneStyle, width: 600, height: 560 },
    selectable: false,
    draggable: false,
  },
  {
    id: "script",
    type: "workflow",
    parentId: "story-zone",
    extent: "parent",
    position: { x: 28, y: 102 },
    data: {
      kind: "script",
      title: "剧本解析",
      subtitle: "角色 · 情节 · 冲突 · 主题",
      status: "complete",
      outputType: "script-analysis",
      accepts: ["text"],
    },
    style: { width: 142, height: 360 },
  },
  {
    id: "story",
    type: "workflow",
    parentId: "story-zone",
    extent: "parent",
    position: { x: 238, y: 102 },
    data: {
      kind: "story",
      title: "故事脉络",
      subtitle: "关键事件与结构梳理",
      status: "complete",
      outputType: "narrative",
      accepts: ["script-analysis"],
    },
    style: { width: 144, height: 360 },
  },
  {
    id: "world",
    type: "workflow",
    parentId: "visual-zone",
    extent: "parent",
    position: { x: 28, y: 102 },
    data: {
      kind: "world",
      title: "世界观设定",
      subtitle: "风格 · 色彩 · 场景参考",
      status: "complete",
      outputType: "world-reference",
      accepts: ["narrative"],
      images: ["/assets/world-rain-courtyard.png", "/assets/world-temple-night.png"],
    },
    style: { width: 158, height: 360 },
  },
  {
    id: "characters",
    type: "workflow",
    parentId: "visual-zone",
    extent: "parent",
    position: { x: 254, y: 102 },
    data: {
      kind: "characters",
      title: "角色定妆",
      subtitle: "主要角色造型与表情",
      status: "complete",
      model: "Seedream 5.0",
      outputType: "character-reference",
      accepts: ["world-reference", "image"],
      images: [
        "/assets/character-woman.png",
        "/assets/character-man.png",
        "/assets/character-elder.png",
        "/assets/character-rival.png",
      ],
    },
    style: { width: 158, height: 360 },
  },
  {
    id: "storyboard",
    type: "workflow",
    parentId: "shot-zone",
    extent: "parent",
    position: { x: 28, y: 102 },
    data: {
      kind: "storyboard",
      title: "分镜规划",
      subtitle: "已规划 26 个镜头",
      status: "approval",
      model: "Doubao Seed 2.0 Pro",
      outputType: "storyboard",
      accepts: ["character-reference", "world-reference", "narrative"],
      images: [
        "/assets/world-rain-courtyard.png",
        "/assets/character-woman.png",
        "/assets/world-temple-night.png",
        "/assets/character-man.png",
      ],
    },
    style: { width: 260, height: 360 },
  },
  {
    id: "video",
    type: "workflow",
    parentId: "shot-zone",
    extent: "parent",
    position: { x: 330, y: 102 },
    data: {
      kind: "video",
      title: "视频生成",
      subtitle: "生成短片 / 预览 / 调整",
      status: "waiting",
      model: "Seedance Mini",
      outputType: "video",
      accepts: ["storyboard", "image"],
      images: ["/assets/world-temple-night.png"],
    },
    style: { width: 240, height: 360 },
  },
];

const edgeStyle = { stroke: "#73727a", strokeWidth: 1.5 };

export const workflowEdges = [
  ["script", "story"],
  ["story", "world"],
  ["world", "characters"],
  ["characters", "storyboard"],
  ["storyboard", "video"],
].map(([source, target], index) => ({
  id: `edge-${index + 1}`,
  source,
  target,
  type: "smoothstep",
  style: edgeStyle,
  markerEnd: { type: MarkerType.ArrowClosed, color: "#73727a", width: 14, height: 14 },
}));
